name: firebase_dart_ui.example
description: Firebase UI wrapper Example
version: 0.0.14
environment:
  sdk: '>2.0.0 <3.0.0'

dependencies:
  angular:  ^5.0.0
  firebase: ^7.3.0
  firebase_dart_ui:
    path: ../../firebase_dart_ui


dev_dependencies:
  build_runner: ^1.9.0
  build_web_compilers: ^2.10.0
